Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.hostname = "test"
    config.vm.network "forwarded_port", guest: 80, host: 8082

    config.vm.provision "pre-provision", type: "shell", inline: <<-SHELL 
    sudo apt-get update
    sudo apt-get install -y curl
    curl -sl https://deb.nodesource.com/setup_12.x | sudo -E bash -
    SHELL
    ####### Install Puppet Agent #######
    config.vm.provision "shell", path: "./bootstrap.sh"
    ####### Provision #######
    config.vm.provision "puppet" do |puppet|
      puppet.module_path = "./site"
      puppet.options = "--verbose --debug"
    end
  end