
# before vagrant plugin install vagrant-puppet-install
# This part to solve error "undefined method `[]' for nil:NilClass (NoMethodError)"" when running with puppet provisioing
class Hash
  def slice(*keep_keys)
    h = {}
    keep_keys.each { |key| h[key] = fetch(key) if has_key?(key) }
    h
  end unless Hash.method_defined?(:slice)
  def except(*less_keys)
    slice(*keys - less_keys)
  end unless Hash.method_defined?(:except)
end

#----------------------------------------------------------------#
Vagrant.configure("2") do |config|
  

  config.vm.hostname = 'vagrant-test'

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/myvagrantkey'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    override.vm.allowed_synced_folder_types = :rsync

    provider.token = ENV['DTOKEN']  # export the token on terminal first
    provider.image = 'ubuntu-18-04-x64'
    provider.region = 'nyc1'
    provider.size = 's-1vcpu-1gb'
    provider.setup = false
  end

  # installing puppet from shell provisioner
  config.vm.provision "shell", path: "./bootstrap.sh"
  # prvisioning with puppet
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "./site"
    puppet.options = "--verbose --debug"
  end
end
