#Vagrant.configure("2") do |config|
 # config.vm.box = "bento/centos-7.5"
  #config.vm.network "forwarded_port", guest: 80, host: 8084
  ####### Install Puppet Agent #######
  #config.vm.provision "shell", path: "./bootstrap.sh"
  ####### Provision #######
  #config.vm.provision "puppet" do |puppet|
   # puppet.module_path = "./site"
    #puppet.options = "--verbose --debug"
  #end
#end


# naming the host machines 

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.hostname = "dk-ord-web01"
  config.vm.network "forwarded_port", guest: 80, host: 8082
  ####### Install Puppet Agent #######
  config.vm.provision "shell", path: "./bootstrap.sh"
  ####### Provision #######
  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "./site"
    puppet.options = "--verbose --debug"
  end
end
