

nodes = [
  { :hostname => 'appserver', :ip => '192.168.56.2'},
  { :hostname => 'dbserver',  :ip => '192.168.56.3'},
  { :hostname => 'web',       :ip => '192.168.56.4',  :g_port => '80',  :h_port => '8080'},
  { :hostname => 'tst0',      :ip => '192.168.56.5'},
  { :hostname => 'tst1',      :ip => '192.168.56.6'},
  { :hostname => 'tst2',      :ip => '192.168.56.7'}
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "bento/ubuntu-18.04"
      nodeconfig.vm.hostname = node[:hostname]
      if node[:hostname] == 'web'  
        nodeconfig.vm.network :forwarded_port, guest: node[:g_port], host: node[:h_port] 
      end
      nodeconfig.vm.network :private_network, ip: node[:ip]
    end
  end
  ####### Install Puppet Agent #######
  config.vm.provision "shell", path: "./bootstrap.sh"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "puppet/modules"
  end
end
