Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.provision "bootstarp", type: "shell", inline: <<-SHELL 
    sudo apt-get update
    sudo apt-get install -y curl git
    curl -sl https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo apt-get install -y build-essential
    SHELL
end